### ISSUE TITLE
Migrating back to Email Auth

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/KnowYourDonor#26]
Phone Auth does not satisfies the need of the app :(

**Comment by arteevraina** [comment]
https://medium.com/flutter-community/flutter-firebase-login-using-provider-package-54ee4e5083c7
This link is for reference.

**Comment by gargk747** [comment]
Hey @arteevraina Can i work on this issue?

**Comment by arteevraina** [comment]
@gargk747 I am currently unassigning you this issue. As I have started working on this, this issue will not be part of `crossWoC`. Did you had any progress with the issue ?
