### ISSUE TITLE
Add regex for Email Validation

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/KnowYourDonor#28]
Write a function for validating the email address when the user enters the email address.
For example, you can refer https://github.com/arteevraina/KnowYourDonor/blob/master/lib/constants/validators.dart

**Comment by avishmehta68710** [comment]
Hi i would like to work on the issue

**Comment by arteevraina** [comment]
@avishmehta68710 done !

**Comment by avishmehta68710** [comment]
Hi 
i added the code for email checking using regex and the app runs successfully but still i am not able to create pr because of test failures. can you tell me why are these test failing.

**Comment by arteevraina** [comment]
Fixed by : #36
