### ISSUE TITLE
Connect Cloud Firestore to the App

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/KnowYourDonor#34]
Cloud Firestore is NoSQL database. We need to save the data of the users like Phone Number , Blood Group etc. So we need to connect to a database.

**Comment by harshsinghs1058** [comment]
hey do i just have to create functions for this task...

**Comment by harshsinghs1058** [comment]
hey do i just have to create the functions for this task...

**Comment by arteevraina** [comment]
No, I guess to need to apply some settings in the code (preferably android folder) and you are good to go.

**Comment by harshsinghs1058** [comment]
assign me this ..
