### ISSUE TITLE
Improve the UI of the Home Page

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/KnowYourDonor#35]
Currently, the UI of the home page does not look good with only two buttons on it. You have to improve the UI of the home page by adding SVGs, animations, and other stuff you feel would suit the app. Please let us know the things you are going to add before working on the issue.

**Comment by hemangdtu** [comment]
Hello, I would like to work on this issue and develop the below given UI.
![Homepage UI](https://user-images.githubusercontent.com/55807508/108053579-9ba89a00-7073-11eb-9fd3-8b7054919999.jpg)

**Comment by arteevraina** [comment]
@hemangdtu What are you going to display in the images?

**Comment by hemangdtu** [comment]
Sir I can add some facts related to blood donation in that section.

**Comment by arteevraina** [comment]
> Sir I can add some facts related to blood donation in that section.

Yes, Make sure you use the colors defined in the colors.dart file.

**Comment by arteevraina** [comment]
Hey @hemangdtu ! I have just updated the home page in the app with the mockup you posted above. But still everything is not complete with the UI. Any kind of help would be appreciated :)

**Comment by hemangdtu** [comment]
Sure sir, let me check go through the changes.
