### ISSUE TITLE
Create Issue and PR Templates

### ISSUE THREAD

**Issue by muthuannamalai12** [arteevraina/KnowYourDonor#37]
Would like to add issue and pr templates to these project that will basically explain the type of issue and its description and also the type of pr the set of checklist that it obeys and its description

Kindly assign this to me as a part of Cross-Woc. I would love to do it

**Comment by arteevraina** [comment]
Yes, this will be a good addition. Can you share the template here before sending a patch ?

**Comment by muthuannamalai12** [comment]
> Yes, this will be a good addition. Can you share the template here before sending a patch ?

Issue Template : 

![Issue](https://user-images.githubusercontent.com/64524822/107934009-82d1b300-6fa5-11eb-9a78-abadc5ec261b.jpeg)

PR Template :

![Screenshot (41)](https://user-images.githubusercontent.com/64524822/107934371-fb387400-6fa5-11eb-8386-d03ff5cb9b79.png)
![Screenshot (42)](https://user-images.githubusercontent.com/64524822/107934375-fd023780-6fa5-11eb-8b5a-3a1402265989.png)

**Comment by muthuannamalai12** [comment]
> Yes, this will be a good addition. Can you share the template here before sending a patch ?

Issue Template : 

![Issue](https://user-images.githubusercontent.com/64524822/107934009-82d1b300-6fa5-11eb-9a78-abadc5ec261b.jpeg)

PR Template :

![Screenshot (41)](https://user-images.githubusercontent.com/64524822/107934371-fb387400-6fa5-11eb-8386-d03ff5cb9b79.png)
![Screenshot (42)](https://user-images.githubusercontent.com/64524822/107934375-fd023780-6fa5-11eb-8b5a-3a1402265989.png)

**Comment by arteevraina** [comment]
@muthuannamalai12 Looks Good! Feel free to contribute a patch :)

**Comment by arteevraina** [comment]
Thanks @muthuannamalai12 ! Closing this :)
