### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [arteevraina/KnowYourDonor#38]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc.

**Comment by arteevraina** [comment]
@antrikshmisri Do you think we need this ?

**Comment by antrikshmisri** [comment]
@arteevraina  Sure why not

**Comment by arteevraina** [comment]
@arteevraina @muthuannamalai12 I think we don't need this as of now. But maybe in the future, it may be required.

**Comment by muthuannamalai12** [comment]
> @arteevraina @muthuannamalai12 I think we don't need this as of now. But maybe in the future, it may be required.

Ok. Thank You
