### ISSUE TITLE
Add Images in Carousel in Home Page

### ISSUE THREAD

**Issue by arteevraina** [arteevraina/KnowYourDonor#49]
The idea is to add show some images in the carousel on the home page in the form of some facts related to Blood Donation.

**Comment by javiercaamano** [comment]
Hi Arteev, have you the images or I have to serch ones?

**Comment by arteevraina** [comment]
Hello @javiercaamano ! Yes, you have to search some images which contains the facts related to Blood Donation and then add them :)

**Comment by pranavi79** [comment]
if this issue is open, can I work on that?

**Comment by arteevraina** [comment]
> if this issue is open, can I work on that?

Hey @pranavi79! Welcome to the repo. Yes, you can work on this issue :)

**Comment by arteevraina** [comment]
> if this issue is open, can I work on that?

Hey @pranavi79! Welcome to the repo. Yes, you can work on this issue :)

**Comment by arteevraina** [comment]
Fixed !
